server:
  port: 8883
spring:
  gson:
    enable-complex-map-key-serialization: true
  application:
    name: learn
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: elastic:9200
  elasticsearch:
    rest:
      uris: elastic:9200
  http:
    converters:
      preferred-json-mapper: gson
eureka:
  instance:
    hostname: learn
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8880/eureka/