server:
  port: 8882
spring:
  application:
    name: gateway
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: 192.168.0.101:9200
  elasticsearch:
    rest:
      uris: 192.168.0.101:9200
eureka:
  instance:
    hostname: 192.168.0.101
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8880/eureka/