server:
  port: 8884
spring:
  gson:
    enable-complex-map-key-serialization: true
  application:
    name: scheduler
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
  elasticsearch:
    rest:
      uris: localhost:9200
  mvc:
    converters:
      preferred-json-mapper: gson
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8880/eureka/