server:
  port: 8080
spring:
  application:
    name: Zuul
eureka:
  instance:
    hostname: zuul
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8880/eureka/
zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-services: '*'
  routes:
    #remove later
    database-manager:
      path: /dbm/**
      serviceId: database-manager
      stripPrefix: true
    gateway:
      path: /api/**
      serviceId: gateway
      stripPrefix: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ReadTimeout: 60000
  connection-timeout: 30000