version: '3.7'

services:

#  elastic:
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.0
#    environment:
#      - "discovery.type=single-node"
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms1000m -Xmx1000m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - dev-elastic-data:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#    logging:
#      options:
#        max-size: 5m
#    networks:
#      - dev
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana-oss:7.6.0
#    environment:
#      ELASTICSEARCH_HOSTS: http://elastic:9200
#    volumes:
#      - dev-kibana:/usr/share/kibana
#    ports:
#      - 5601:5601
#    networks:
#      - dev
#    logging:
#      options:
#        max-size: 5m
#  assistant-relay:
#    #    build: ../assistant-relay-3.2.0
#    image: obp3ter/smart-home-remote:assistant-relay
#    ports:
#      - 3000:3000
#    volumes:
#      - dev-assistant-relay:/usr/share/assistant-relay
#    networks:
#      - dev
#    logging:
#      options:
#        max-size: 5m
  web:
    #    build: ../web
    image: obp3ter/smart-home-remote:web
    ports:
      - 4200:80
    volumes:
      - dev-web:/usr/share/web
    networks:
      - dev
    logging:
      options:
        max-size: 5m
#  eureka:
#    image: obp3ter/smart-home-remote:eureka
##    build: ../eureka
#    volumes:
#      - dev-eureka:/usr/share/eureka
#    ports:
#      - 8880:8880
#    networks:
#      - dev
#    logging:
#      options:
#        max-size: 5m
#  dbm:
#    image: obp3ter/smart-home-remote:dbm
#    volumes:
#      - dev-dbm:/usr/share/dbm
#    ports:
#      - 8881:8881
#    networks:
#      - dev
#    logging:
#      options:
#        max-size: 5m
#  gateway:
#    image: obp3ter/smart-home-remote:gateway
##    build: ../gateway
#    volumes:
#      - dev-gateway:/usr/share/gateway
#    ports:
#      - 8882:8882
#    networks:
#      - dev
#    logging:
#      options:
#        max-size: 5m
#  learn:
#    image: obp3ter/smart-home-remote:learn
##    build: ../learn
#    volumes:
#      - dev-learn:/usr/share/learn
#    ports:
#    - 8883:8883
#    networks:
#      - dev
#    logging:
#      options:
#        max-size: 5m
#  scheduler:
#    image: obp3ter/smart-home-remote:scheduler
##    build: ../scheduler
#    volumes:
#      - dev-scheduler:/user/share/scheduler
#    ports:
#    - 8884:8884
#    networks:
#      - dev
#    logging:
#      options:
#        max-size: 5m
#  zuul:
#    image: obp3ter/smart-home-remote:zuul
#    volumes:
#    - dev-zuul:/usr/share/zuul
#    ports:
#    - 8080:8080
#    networks:
#      - dev
#    logging:
#      options:
#        max-size: 5m
networks:
  dev:



volumes:
  dev-elastic-data:
  dev-kibana:
  dev-dbm:
  dev-eureka:
  dev-gateway:
  dev-learn:
  dev-scheduler:
  dev-zuul:
  dev-assistant-relay:
  dev-web:

