version: '3.7'

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.0
    environment:
      - "discovery.type=single-node"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1000m -Xmx1000m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dev-elastic-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    logging:
      options:
        max-size: 5m
    networks:
      - dev

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.6.0
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
    volumes:
      - dev-kibana:/usr/share/kibana
    ports:
      - 5601:5601
    networks:
      - dev
    logging:
      options:
        max-size: 5m
      
networks:
  dev:

volumes:  
  dev-elastic-data:
  dev-kibana:
