server:
  port: 8880
spring:
  application:
    name: Eureka-Discovery
eureka:
  instance:
    hostname: eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0