server:
  port: 8880
spring:
  application:
    name: Eureka-Discovery
eureka:
  instance:
    hostname: 192.168.0.101
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0