server:
  port: 8881
spring:
  application:
    name: database-manager
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: elastic:9200
  elasticsearch:
    rest:
      uris: elastic:9200
eureka:
  instance:
    hostname: dbm
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8880/eureka/